### ISSUE TITLE
Ругается ли gps на формат?

### ISSUE THREAD

**Issue by IIIu6ko** [agragregra/Gulp-Image-Compressor#2]
Если использовать этот метод сжатия, то ругается ли на формат google page speed?
Там рекомендации по поводу webp выскакивают.

**Comment by agragregra** [comment]
Это один из лучших методов сжатия, в том числе и для PageSpeed.
webp хорош, но что делать с пользователями iPhone? Пока не понятно.

**Comment by IIIu6ko** [comment]
> 
> 
> Это один из лучших методов сжатия, в том числе и для PageSpeed.
> webp хорош, но что делать с пользователями iPhone? Пока не понятно.

`
<picture class="header__logo">
    <source srcset="imgs/header/header__logo-img.webp" type="image/webp">
    <img class="header__logo-img" src="imgs/header/header__logo-img.png" alt="">
</picture>
`

**Comment by agragregra** [comment]
Много городьбы.

**Comment by IIIu6ko** [comment]
> 
> 
> Много городьбы.

Всего одна обёртка + второе изображение для браузеров, которые не поддерживают.
+ можно медиазапросы писать для изображений:
```
<picture>
    <source srcset="imgs/header/header__bg.webp" type="image/webp" media="(min-width: 768px)">
    <source srcset="imgs/header/header__bg.jpg" type="image/jpeg" media="(min-width: 768px)">
    <source srcset="imgs/header/header__bg-768.webp" type="image/webp" media="(max-width: 767.98px)">
    <source srcset="imgs/header/header__bg-768.jpg" type="image/jpeg" media="(max-width: 767.98px)">
    <img class="header__bg" src="imgs/header/header__bg.jpg" alt="header background">
</picture>
```

**Comment by agragregra** [comment]
Не айс.

**Comment by IIIu6ko** [comment]
> 
> 
> Не айс.

Понял.

А что скажешь про [smushit](https://www.npmjs.com/package/gulp-smushit)? Не тестил его?
